bulk insert Item from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\Item.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert ItemStatus from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\ItemStatus.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert Job from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\Job.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert Employee from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\Employee.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert FoodsAndDrinks from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\FoodsAndDrinks.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert Customer from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\Customer.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert Room from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\Room.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')
bulk insert RoomType from 'C:\Users\PC 08\source\repos\Timer_LKS_Hotel\DB\Data\RoomType.csv' with (firstrow=2, fieldterminator=';', rowterminator='\n')